import Head from 'next/head';
import Image from 'next/image';
import {signIn, useSession} from "next-auth/react"
import Profile from '../components/profile';
import styles from '../styles/Home.module.css';
import Unauthorized from "../components/unauthorized";

export default function Home() {

    const { data: session } = useSession()
    const callAPI = async () => {
        try {
            const res = await fetch(
                process.env.API_URL || "http://localhost:8000/",
                {
                    method: 'GET',
                    headers: {
                        'Authorization': 'Bearer ' + session.token,
                    },
                }
            );
            const data = await res.json();
            console.log(data);
        } catch (err) {
            console.log(err);
        }
    };
        return (
          <>
              {session && (
                  <>
                      <code>{JSON.stringify(session, null, 2)}</code>
                      <div className={styles.container}>
                          <Head>
                              <title>Create Next App</title>
                              <meta name="description" content="Generated by create next app" />
                              <link rel="icon" href="/favicon.ico" />
                          </Head>

                          <main className={styles.main}>
                              {session.token}

                              Button to send request to localhost:8000/ with token in header
                                <button onClick={callAPI}>Send request to localhost:8000/ with token in header</button>

                              <Profile />
                          </main>

                      </div>
                  </>
              )}
              {!session && (
                  Unauthorized()
              )}
          </>
        );

}
